// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvXVc3tZ0T_Kc2Aqc7-OV1f4YQqRbZSek',
    appId: '1:163157963278:web:42fa30b1413a45cf54025f',
    messagingSenderId: '163157963278',
    projectId: 'art-portfolio-2eb47',
    authDomain: 'art-portfolio-2eb47.firebaseapp.com',
    storageBucket: 'art-portfolio-2eb47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdHAh3RFlyyphAETgIY4KZft8KYZzRdGQ',
    appId: '1:163157963278:android:c61eb9fe16e5a07754025f',
    messagingSenderId: '163157963278',
    projectId: 'art-portfolio-2eb47',
    storageBucket: 'art-portfolio-2eb47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsWsYvBsTDPCHX93EsuZ7wB0FiwkS0Awo',
    appId: '1:163157963278:ios:db818d4171368c8b54025f',
    messagingSenderId: '163157963278',
    projectId: 'art-portfolio-2eb47',
    storageBucket: 'art-portfolio-2eb47.appspot.com',
    iosBundleId: 'com.example.artPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsWsYvBsTDPCHX93EsuZ7wB0FiwkS0Awo',
    appId: '1:163157963278:ios:db818d4171368c8b54025f',
    messagingSenderId: '163157963278',
    projectId: 'art-portfolio-2eb47',
    storageBucket: 'art-portfolio-2eb47.appspot.com',
    iosBundleId: 'com.example.artPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvXVc3tZ0T_Kc2Aqc7-OV1f4YQqRbZSek',
    appId: '1:163157963278:web:5470c539c20e028154025f',
    messagingSenderId: '163157963278',
    projectId: 'art-portfolio-2eb47',
    authDomain: 'art-portfolio-2eb47.firebaseapp.com',
    storageBucket: 'art-portfolio-2eb47.appspot.com',
  );
}
